/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gallery;

import java.awt.Cursor;
import java.awt.Graphics2D;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author saeid
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     private BufferedImage resizeImage(BufferedImage originalImage, int width, int height, int type) throws IOException {  
        BufferedImage resizedImage = new BufferedImage(width, height, type);  
        Graphics2D g = resizedImage.createGraphics();  
        g.drawImage(originalImage, 0, 0, width, height, null);  
        g.dispose();  
        return resizedImage;  
    }  
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Toools = new javax.swing.JPanel();
        Opener = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        IconPanel = new javax.swing.JPanel();
        A1 = new javax.swing.JLabel();
        A2 = new javax.swing.JLabel();
        A3 = new javax.swing.JLabel();
        A4 = new javax.swing.JLabel();
        A5 = new javax.swing.JLabel();
        A6 = new javax.swing.JLabel();
        A7 = new javax.swing.JLabel();
        A8 = new javax.swing.JLabel();
        A9 = new javax.swing.JLabel();
        A10 = new javax.swing.JLabel();
        A15 = new javax.swing.JLabel();
        A13 = new javax.swing.JLabel();
        A11 = new javax.swing.JLabel();
        A14 = new javax.swing.JLabel();
        A12 = new javax.swing.JLabel();
        A16 = new javax.swing.JLabel();
        A17 = new javax.swing.JLabel();
        A18 = new javax.swing.JLabel();
        A19 = new javax.swing.JLabel();
        A20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Toools.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ابزار", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        Opener.setText("باز کردن");
        Opener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TooolsLayout = new javax.swing.GroupLayout(Toools);
        Toools.setLayout(TooolsLayout);
        TooolsLayout.setHorizontalGroup(
            TooolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TooolsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Opener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TooolsLayout.setVerticalGroup(
            TooolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TooolsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Opener, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

        javax.swing.GroupLayout IconPanelLayout = new javax.swing.GroupLayout(IconPanel);
        IconPanel.setLayout(IconPanelLayout);
        IconPanelLayout.setHorizontalGroup(
            IconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IconPanelLayout.createSequentialGroup()
                        .addGroup(IconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(IconPanelLayout.createSequentialGroup()
                                .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(IconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(IconPanelLayout.createSequentialGroup()
                                    .addComponent(A11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(A12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(A13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(A14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IconPanelLayout.createSequentialGroup()
                                    .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(A8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(A9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(IconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A10, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(IconPanelLayout.createSequentialGroup()
                        .addComponent(A16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(A17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(A18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(A19, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(A20, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        IconPanelLayout.setVerticalGroup(
            IconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IconPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(IconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IconPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A20, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(IconPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Toools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(Toools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   //آرایه ای جهت کمک به عمل قرار دادن عکس ها در کنار هم که نشان میدهد کدام جا خالی است و عکس میتواند وارد شود
    int[] ww=new int[]{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
    //عکس های که وارد شده جهت استفاده در کلاس دیگر
    public BufferedImage[] AllImages=new BufferedImage[20];
   //یک شی از کلاس دیگر برای نماش عکس در اندازه بزرگ
    public  NewJFrame f=new NewJFrame();
    
    private void OpenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenerActionPerformed

        //set default dir to user home
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.home"));
        //items in filter dropdown box
        FileFilter excelType = new FileNameExtensionFilter(".JPG", "JPG");
        fileChooser.addChoosableFileFilter(excelType);
        //default (initial) filter predefined in dropdown box
        fileChooser.setFileFilter(excelType);
        //initial file name
        fileChooser.setSelectedFile(new File("عکس"));
        //clear "All files" from dropdown filter box
        fileChooser.setAcceptAllFileFilterUsed(false);
        //open filechooser dialog
        int response = fileChooser.showSaveDialog(null);
        if(response == JFileChooser.APPROVE_OPTION)
        {
            
            try {
                final BufferedImage img=ImageIO.read(fileChooser.getSelectedFile());
                    
                if(ww[1]==0){
                    A1.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));

                    ww[1]=1;
                                       AllImages[0]=resizeImage(img, 860, 514, 5);

                    A1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A1.addMouseListener(new MouseAdapter()  
                            {  
                                //تابعی جهت کنترل عکس هایی که بر رو آن ها کلیک شده و در کلاس دیگر با اندازه بزرگ باز میشوند 
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                        
                                       f.show(resizeImage(img, 799, 555, 5),AllImages);
                                       
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    
                    ww[2]=0;
                }
                    else if(ww[2]==0){
                  
                          A2.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[2]=1;
                                       AllImages[1]=resizeImage(img, 860, 514, 5);

                    A2.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A2.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[3]=0;
                     }
                    else if(ww[3]==0){
                    A3.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[3]=1;
                                       AllImages[2]=resizeImage(img, 860, 514, 5);

                    A3.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A3.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                   
                    ww[4]=0;
                } 
                    else  if(ww[4]==0){
                    A4.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[4]=1;
                                       AllImages[3]=resizeImage(img, 860, 514, 5);

                    A4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A4.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    
                    ww[5]=0;
                     }
                 
                    else if(ww[5]==0){
                    A5.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[5]=1;
                                       AllImages[4]=resizeImage(img, 860, 514, 5);

                    A5.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A5.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[6]=0;
                } 
                    else  if(ww[6]==0){
                    A6.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[6]=1;
                                       AllImages[5]=resizeImage(img, 860, 514, 5);

                    A6.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A6.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[7]=0;
                     }
                     else  if(ww[7]==0){
                    A7.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[7]=1;
                                       AllImages[6]=resizeImage(img, 860, 514, 5);

                    A7.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A7.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[8]=0;
                     }
                     else  if(ww[8]==0){
                    A8.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[8]=1;
                                       AllImages[7]=resizeImage(img, 860, 514, 5);

                    A8.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A8.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[9]=0;
                     }
                     else  if(ww[9]==0){
                    A9.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[9]=1;
                                       AllImages[8]=resizeImage(img, 860, 514, 5);

                    A9.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A9.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[10]=0;
                     }
                     else  if(ww[10]==0){
                    A10.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[10]=1;
                                       AllImages[9]=resizeImage(img, 860, 514, 5);

                    A10.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A10.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[11]=0;
                     }
                     else  if(ww[11]==0){
                    A11.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[11]=1;
                                       AllImages[10]=resizeImage(img, 860, 514, 5);

                    A11.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A11.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                   
                    ww[12]=0;
                     }
                     else  if(ww[12]==0){
                    A12.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));

                    ww[12]=1;
                                       AllImages[11]=resizeImage(img, 860, 514, 5);

                    A12.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A12.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[13]=0;
                     }
                     else  if(ww[13]==0){
                    A13.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[13]=1;
                                       AllImages[12]=resizeImage(img, 860, 514, 5);

                    A13.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A13.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[14]=0;
                     }
                     else  if(ww[14]==0){
                    A14.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[14]=1;
                                       AllImages[13]=resizeImage(img, 860, 514, 5);

                    A14.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A14.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[15]=0;
                     }
                     else  if(ww[15]==0){
                    A15.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[15]=1;
                                       AllImages[14]=resizeImage(img, 860, 514, 5);

                    A15.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A15.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[16]=0;
                     }
                     else  if(ww[16]==0){
                    A16.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[16]=1;
                                       AllImages[15]=resizeImage(img, 860, 514, 5);

                    A16.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A16.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[17]=0;
                     } else  if(ww[17]==0){
                    A17.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[17]=1;
                                       AllImages[16]=resizeImage(img, 860, 514, 5);

                    A17.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A17.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[18]=0;
                     } else  if(ww[18]==0){
                    A18.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));

                    ww[18]=1;

                                       AllImages[17]=resizeImage(img, 860, 514, 5);
                    A18.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A18.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[19]=0;
                     } else  if(ww[19]==0){
                    A19.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[19]=1;
                                       AllImages[18]=resizeImage(img, 860, 514, 5);

                    A19.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A19.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 860, 514, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[20]=0;
                     } else  if(ww[20]==0){
                    A20.setIcon( new ImageIcon(resizeImage(img, 150, 140, 5)));
                    ww[20]=1;
                    AllImages[19]=resizeImage(img, 860, 514, 5);
                    A20.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));

                    A20.addMouseListener(new MouseAdapter()  
                            {  
                                public void mouseClicked(MouseEvent e)  
                                {  
                                   // you can open a new frame here as
                                   // i have assumed you have declared "frame" as instance variable
                                   NewJFrame f=new NewJFrame();
                                    try {
                                       f.show(resizeImage(img, 799,555, 5),AllImages);
                                    } catch (IOException ex) {
                                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                                   f.setVisible(true);

                                }  
                            });
                    ww[1]=0;
                  
                        
                        
                    } 
                                   
                
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_OpenerActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel A1;
    public javax.swing.JLabel A10;
    public javax.swing.JLabel A11;
    public javax.swing.JLabel A12;
    public javax.swing.JLabel A13;
    public javax.swing.JLabel A14;
    public javax.swing.JLabel A15;
    public javax.swing.JLabel A16;
    public javax.swing.JLabel A17;
    public javax.swing.JLabel A18;
    public javax.swing.JLabel A19;
    public javax.swing.JLabel A2;
    public javax.swing.JLabel A20;
    public javax.swing.JLabel A3;
    public javax.swing.JLabel A4;
    public javax.swing.JLabel A5;
    public javax.swing.JLabel A6;
    public javax.swing.JLabel A7;
    public javax.swing.JLabel A8;
    public javax.swing.JLabel A9;
    private javax.swing.JPanel IconPanel;
    private javax.swing.JButton Opener;
    private javax.swing.JPanel Toools;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
